---
title: "LM random forest application"
author: "Robyn Sumner"
date: "2024-01-19"
output: html_document
---

# This code was used for joining the GRADES reaches and the global predictors to the Manchester and Liverpool dataset, using Rocher-Ros et al.'s (2023) preprocessing code.

```{r}
library(tidyverse)
library(RCurl)
library(sf)
library(XML)
library(rworldmap)
library(leaflet)
library(lwgeom)

sites_df <- read_csv("/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/GRiMeDB.rda/LM_site.csv")
papers_df <- read_csv("/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/GRiMeDB.rda/LM_source.csv")
conc_df <- read_csv("/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/GRiMeDB.rda/LM_concentration.csv")
flux_df <- read_csv("/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/GRiMeDB.rda/LM_flux.csv")

files <- list.files("/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/RiverMethaneFlux-master/RiverMethaneFlux-master/data/raw/grades")[grepl(".shp$", list.files("/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/RiverMethaneFlux-master/RiverMethaneFlux-master/data/raw/grades"))]


shape_files <- paste("/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/RiverMethaneFlux-master/RiverMethaneFlux-master/data/raw/grades", files[grepl(".shp$", files)], sep="/") 

shapes_rivers <- shape_files[grepl("riv_", shape_files)]

shapes_catchments <- shape_files[grepl("cat", shape_files)]

```


```{r}
coords2continent = function(lat, lon)
{  
  points <- data.frame(lon, lat)
  countriesSP <- getMap(resolution='low')
  #countriesSP <- getMap(resolution='high') #you could use high res map from rworldxtra if you were concerned about detail
  
  # converting points to a SpatialPoints object
  # setting CRS directly to that from rworldmap
  pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  
  
  
  # use 'over' to get indices of the Polygons object containing each point 
  indices = over(pointsSP, countriesSP)
  
  #indices$continent   # returns the continent (6 continent model)
  indices$REGION   # returns the continent (7 continent model)
  #indices$ADMIN  #returns country name
  #indices$ISO3 # returns the ISO3 code 
}


sites_meth <- sites_df %>%  
  mutate(lat = ifelse(is.na(Latitude_snapped) == TRUE, Latitude, Latitude_snapped),
         lon = ifelse(is.na(Longitude_snapped) == TRUE, Longitude, Longitude_snapped)) %>% 
  dplyr::select(Site_ID, lat, lon) %>%
  drop_na(lat) %>% 
  mutate(continent =  coords2continent(lat, lon) )

#check if there are some without continent
sites_meth %>% 
  filter(is.na(continent) == TRUE) %>% 
  print(n=60)

#We need to fix those sites with unassigned continent
sites_meth <- sites_meth %>% 
  mutate(
    #this needed some manual fixing in some cases
    continent = case_when(lat > 5 & lon > 60 ~ "Asia",
                          lat < 4.7 & lon > 108 ~ "Oceania",
                          lon < -30 & lon > -133 & lat > 15 ~"North America",
                          lon < -30 & lon > -133 & lat < 15 ~"South America",
                          lon > 0 & lon < 20 & lat < 15 ~"Africa",
                          lon > -30 & lon < 60 & lat > 15 ~ "Europe",
                          lat < 1 & lon < 103 & lon > 96 ~ "Oceania",
                          TRUE ~ continent)) %>% 
  st_as_sf( coords = c("lon", "lat"), crs = 4326)
  
  

```


```{r}
## #2, is Europe ----
# read the GRADES shapefile 
europe <- read_sf(shapes_rivers[2]) %>% st_set_crs(4326)

sites_in_europe <- sites_meth %>% 
  filter(continent %in% c("Europe"))

#find the nearest GRADES network
nearest <- st_nearest_feature(sites_in_europe, europe)


#get the distance that has been snapped as a QAQC
distance_snapped <- st_distance(sites_in_europe, europe[nearest,], by_element = TRUE) %>% 
  as.vector()

summary(distance_snapped)

#get the snapped COMID and ancillary variables 
sites_in_europe <- sites_in_europe %>% 
  mutate(COMID = europe[nearest,]$COMID,
         lengthkm = europe[nearest,]$Length,
         slope_grades = europe[nearest,]$Slope,
         uparea = europe[nearest,]$DSContArea,
         order = europe[nearest,]$strmOrder,
         NextDownID = europe[nearest,]$DSLINKNO, 
         distance_snapped = distance_snapped) 


## Combine all files and write output ----
sites_meth_comid <- rbind(sites_in_europe) %>% 
  mutate(lat = sf::st_coordinates(.)[,1],
         lon = sf::st_coordinates(.)[,2]) %>% 
  st_drop_geometry()

write_csv(sites_meth_comid, "/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/RiverMethaneFlux-master/RiverMethaneFlux-master/data/processed/sites_meth_comid_LM.csv")
```

```{r}
# fix NAs in channel type
sites_df <- sites_df %>% 
  mutate(Channel_type = ifelse(is.na(Channel_type) == TRUE, "normal", Channel_type)) 

sites_clean <- sites_df %>% 
  left_join(sites_meth_comid, by="Site_ID") %>% 
  drop_na(COMID)



## attach the COMID to the concentration df and keep useful variables. we also fix NAs from CH4mean to close to equilibrium
conc_df_comids <- conc_df %>% 
  filter(Site_ID %in% sites_clean$Site_ID) %>% 
  left_join(sites_clean, by="Site_ID")# %>% 
#  dplyr::select(Site_ID, Aggregated, Channel_type, COMID, distance_snapped, CH4mean, CO2mean,
#                date= Date_start, date_end= Date_end, discharge_measured= Q, WaterTemp_degC, WaterTemp_degC_estimated  )#  %>% 
#  mutate(CH4mean =ifelse(CH4mean < 0.0001, 0.0001, CH4mean)) %>% 
#  drop_na(CH4mean)

# Load GRADES river network with spatial attributes ----
grades_attributes <- read_csv( "C:/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/RiverMethaneFlux-master/RiverMethaneFlux-master/data/processed/grade_attributes.csv", lazy=FALSE) 

#Now attach all the annual variables to each pair of site_obs in the conc df 
grimeDB_attributes <- conc_df_comids %>% 
  left_join(grades_attributes, by="COMID")

colnames(grimeDB_attributes)
colnames(grimeDB_attributes)[grepl("_jan", colnames(grimeDB_attributes))]

grimeDB_attributes$Date_start <- as.Date(grimeDB_attributes$Date_start)

# Now we do the monthly resolved variables, needs some thinking...
# Ok the way is to check the month of each observation and then match the value of a given variable
grimeDB_attributes_mon <- grimeDB_attributes %>% 
  mutate( gw_month = case_when(month(Date_start) == 1 ~ gw_jan,
                               month(Date_start) == 2 ~ gw_feb,
                               month(Date_start) == 3 ~ gw_mar,
                               month(Date_start) == 4 ~ gw_apr,
                               month(Date_start) == 5 ~ gw_may,
                               month(Date_start) == 6 ~ gw_jun,
                               month(Date_start) == 7 ~ gw_jul,
                               month(Date_start) == 8 ~ gw_aug,
                               month(Date_start) == 9 ~ gw_sep,
                               month(Date_start) == 10 ~ gw_oct,
                               month(Date_start) == 11 ~ gw_nov,
                               month(Date_start) == 12 ~ gw_dec),
          k_month =  case_when(month(Date_start) == 1 ~  k_jan,
                               month(Date_start) == 2 ~  k_feb,
                               month(Date_start) == 3 ~  k_mar,
                               month(Date_start) == 4 ~  k_apr,
                               month(Date_start) == 5 ~  k_may,
                               month(Date_start) == 6 ~  k_jun,
                               month(Date_start) == 7 ~  k_jul,
                               month(Date_start) == 8 ~  k_aug,
                               month(Date_start) == 9 ~  k_sep,
                               month(Date_start) == 10 ~ k_oct,
                               month(Date_start) == 11 ~ k_nov,
                               month(Date_start) == 12 ~ k_dec),
          q_month =  case_when(month(Date_start) == 1 ~  q_jan,
                               month(Date_start) == 2 ~  q_feb,
                               month(Date_start) == 3 ~  q_mar,
                               month(Date_start) == 4 ~  q_apr,
                               month(Date_start) == 5 ~  q_may,
                               month(Date_start) == 6 ~  q_jun,
                               month(Date_start) == 7 ~  q_jul,
                               month(Date_start) == 8 ~  q_aug,
                               month(Date_start) == 9 ~  q_sep,
                               month(Date_start) == 10 ~ q_oct,
                               month(Date_start) == 11 ~ q_nov,
                               month(Date_start) == 12 ~ q_dec),
          gpp_month = case_when(month(Date_start) == 1 ~ gpp_jan,
                                month(Date_start) == 2 ~ gpp_feb,
                                month(Date_start) == 3 ~ gpp_mar,
                                month(Date_start) == 4 ~ gpp_apr,
                                month(Date_start) == 5 ~ gpp_may,
                                month(Date_start) == 6 ~ gpp_jun,
                                month(Date_start) == 7 ~ gpp_jul,
                                month(Date_start) == 8 ~ gpp_aug,
                                month(Date_start) == 9 ~ gpp_sep,
                                month(Date_start) == 10 ~ gpp_oct,
                                month(Date_start) == 11 ~ gpp_nov,
                                month(Date_start) == 12 ~ gpp_dec),
          npp_month = case_when(month(Date_start) == 1 ~ npp_jan,
                                month(Date_start) == 2 ~ npp_feb,
                                month(Date_start) == 3 ~ npp_mar,
                                month(Date_start) == 4 ~ npp_apr,
                                month(Date_start) == 5 ~ npp_may,
                                month(Date_start) == 6 ~ npp_jun,
                                month(Date_start) == 7 ~ npp_jul,
                                month(Date_start) == 8 ~ npp_aug,
                                month(Date_start) == 9 ~ npp_sep,
                                month(Date_start) == 10 ~ npp_oct,
                                month(Date_start) == 11 ~ npp_nov,
                                month(Date_start) == 12 ~ npp_dec),
          temp_month = case_when(month(Date_start) == 1 ~ temp_jan,
                                 month(Date_start) == 2 ~ temp_feb,
                                 month(Date_start) == 3 ~ temp_mar,
                                 month(Date_start) == 4 ~ temp_apr,
                                 month(Date_start) == 5 ~ temp_may,
                                 month(Date_start) == 6 ~ temp_jun,
                                 month(Date_start) == 7 ~ temp_jul,
                                 month(Date_start) == 8 ~ temp_aug,
                                 month(Date_start) == 9 ~ temp_sep,
                                 month(Date_start) == 10 ~ temp_oct,
                                 month(Date_start) == 11 ~ temp_nov,
                                 month(Date_start) == 12 ~ temp_dec),
          precip_month = case_when(month(Date_start) == 1 ~ precip_jan/31*365,
                                   month(Date_start) == 2 ~ precip_feb/28*365,
                                   month(Date_start) == 3 ~ precip_mar/31*365,
                                   month(Date_start) == 4 ~ precip_apr/30*365,
                                   month(Date_start) == 5 ~ precip_may/31*365,
                                   month(Date_start) == 6 ~ precip_jun/30*365,
                                   month(Date_start) == 7 ~ precip_jul/31*365,
                                   month(Date_start) == 8 ~ precip_aug/31*365,
                                   month(Date_start) == 9 ~ precip_sep/30*365,
                                   month(Date_start) == 10 ~ precip_oct/31*365,
                                   month(Date_start) == 11 ~ precip_nov/30*365,
                                   month(Date_start) == 12 ~ precip_dec/31*365),
          tavg_month = case_when(month(Date_start) == 1 ~ tavg_jan,
                                 month(Date_start) == 2 ~ tavg_feb,
                                 month(Date_start) == 3 ~ tavg_mar,
                                 month(Date_start) == 4 ~ tavg_apr,
                                 month(Date_start) == 5 ~ tavg_may,
                                 month(Date_start) == 6 ~ tavg_jun,
                                 month(Date_start) == 7 ~ tavg_jul,
                                 month(Date_start) == 8 ~ tavg_aug,
                                 month(Date_start) == 9 ~ tavg_sep,
                                 month(Date_start) == 10 ~ tavg_oct,
                                 month(Date_start) == 11 ~ tavg_nov,
                                 month(Date_start) == 12 ~ tavg_dec),
          runoff_month = case_when(month(Date_start) == 1 ~ runoff_jan,
                                   month(Date_start) == 2 ~ runoff_feb,
                                   month(Date_start) == 3 ~ runoff_mar,
                                   month(Date_start) == 4 ~ runoff_apr,
                                   month(Date_start) == 5 ~ runoff_may,
                                   month(Date_start) == 6 ~ runoff_jun,
                                   month(Date_start) == 7 ~ runoff_jul,
                                   month(Date_start) == 8 ~ runoff_aug,
                                   month(Date_start) == 9 ~ runoff_sep,
                                   month(Date_start) == 10 ~ runoff_oct,
                                   month(Date_start) == 11 ~ runoff_nov,
                                   month(Date_start) == 12 ~ runoff_dec),
          sresp_month = case_when(month(Date_start) == 1 ~ sresp_jan*365, #soil resp is in daily values
                                  month(Date_start) == 2 ~ sresp_feb*365,
                                  month(Date_start) == 3 ~ sresp_mar*365,
                                  month(Date_start) == 4 ~ sresp_apr*365,
                                  month(Date_start) == 5 ~ sresp_may*365,
                                  month(Date_start) == 6 ~ sresp_jun*365,
                                  month(Date_start) == 7 ~ sresp_jul*365,
                                  month(Date_start) == 8 ~ sresp_aug*365,
                                  month(Date_start) == 9 ~ sresp_sep*365,
                                  month(Date_start) == 10 ~ sresp_oct*365,
                                  month(Date_start) == 11 ~ sresp_nov*365,
                                  month(Date_start) == 12 ~ sresp_dec*365),
          aridity_month = case_when(month(Date_start) == 1 ~ aridity_jan,
                                    month(Date_start) == 2 ~ aridity_feb,
                                    month(Date_start) == 3 ~ aridity_mar,
                                    month(Date_start) == 4 ~ aridity_apr,
                                    month(Date_start) == 5 ~ aridity_may,
                                    month(Date_start) == 6 ~ aridity_jun,
                                    month(Date_start) == 7 ~ aridity_jul,
                                    month(Date_start) == 8 ~ aridity_aug,
                                    month(Date_start) == 9 ~ aridity_sep,
                                    month(Date_start) == 10 ~ aridity_oct,
                                    month(Date_start) == 11 ~ aridity_nov,
                                    month(Date_start) == 12 ~ aridity_dec),
          nee_month = case_when(month(Date_start) == 1 ~ nee_jan,
                                month(Date_start) == 2 ~ nee_feb,
                                month(Date_start) == 3 ~ nee_mar,
                                month(Date_start) == 4 ~ nee_apr,
                                month(Date_start) == 5 ~ nee_may,
                                month(Date_start) == 6 ~ nee_jun,
                                month(Date_start) == 7 ~ nee_jul,
                                month(Date_start) == 8 ~ nee_aug,
                                month(Date_start) == 9 ~ nee_sep,
                                month(Date_start) == 10 ~ nee_oct,
                                month(Date_start) == 11 ~ nee_nov,
                                month(Date_start) == 12 ~ nee_dec),
  ) %>%
  dplyr::select(!ends_with(c("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec")))



write_csv(grimeDB_attributes_mon, "/Users/robyn/OneDrive/Documents/1 - Uni of Bristol/Y3 Geography/Dissertation/Data/RiverMethaneFlux-master/RiverMethaneFlux-master/data/processed/LM - Data for Modelling.csv")

```

